workers_dev = true
compatibility_date = "2023-03-02"
account_id = ""
usage_model = "unbound"

main = "build/worker/shim.mjs"
rules = [{ globs=["**/*.wasm"], type = "CompiledWasm", fallthrough = false }]
build = { command = "worker-build --release" }

# Staging environment as default
name = "soroflare-dev"

vars = { ENVIRONMENT = "dev", ASTEROIDS_SEED="8891", SOROBAN_CPU_BUDGET="16000000000" }

kv_namespaces = [
    { binding = "MODULES", id = "da0e5c7abc4d4209b1ec18579a71041c"}, 
]
